spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/notes?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    defer-datasource-initialization: true
#    properties:
#      hibernate: 
#       search: 
#        enabled: true
#        schema_management:
#          strategy: drop-and-create
#        backend:
#          hosts: localhost:9200 
  sql:
    init:
      platform: postgres
      mode: always

jwtSecret: ======================BezKoder=Spring===========================
jwtExpirationMs: 86400000